### ISSUE TITLE
@types/googlemaps is deprecated in favor of @types/google.maps

### ISSUE THREAD

**Issue by Tyresius92** [wellyshen/use-places-autocomplete#1018]
# Feature Request

## Describe the Feature

It looks like the [@types/googlemaps](https://www.npmjs.com/package/@types/googlemaps) package is deprecated in favor of [@types/google.maps](https://www.npmjs.com/package/@types/google.maps).

Unfortunately, I don't have time at the moment to create a PR, but I figured I could at least get it on y'all's radar. 

## Describe the Solution You'd Like

It'd be great to update this package to use the non-deprecated version of the types package. I'm unsure if this would be mainly a documentation change or if there would be changes required in the code. 

## Describe Alternatives You've Considered

It doesn't seem to be broken, so in theory the deprecated package could continue to be used. That seems like not the best idea in the long term, though. 😅 

## Additional Information

None from me.

**Comment by wellyshen** [comment]
It's solved by this [PR](https://github.com/wellyshen/use-places-autocomplete/pull/1030).
