### ISSUE TITLE
getZipCode utility function

### ISSUE THREAD

**Issue by kieryk123** [wellyshen/use-places-autocomplete#106]
# Feature Request

## Describe the Feature

I think "getZipCode" utility function would be very helpful for me and everyone else. For example, I use your hook on my address field and I try to auto-populate zip code on another field. 

Currently, I get results from "getGeocode" and iterate through them and manually take out "postal_code" from "address_components" array.

I hope you understand :)

**Comment by wellyshen** [comment]
@kieryk123 Thank you for this idea. Apart from the "zip code", do you think we should also provide a helper for the `address_components `? For instance, `getAddress().zipCode`, `getAddress().address`?

**Comment by kieryk123** [comment]
@wellyshen I think it will be helpful. I don't know exactly what data Google Maps API provides, but in my opinion, it will be very useful 😄  Let me know when you update the library! 👍

**Comment by wellyshen** [comment]
@kieryk123 Okay, i will let you know when I add it.

**Comment by wellyshen** [comment]
@kieryk123 [Here](https://github.com/wellyshen/use-places-autocomplete#getzipcode) you are, bro.

**Comment by kieryk123** [comment]
Awesome! Thank you 👌
