### ISSUE TITLE
request a new working example

### ISSUE THREAD

**Issue by toppyc4** [wellyshen/use-places-autocomplete#1108]
since reach/combobox is not maintain(got an error when using with react <17) can you give a working example beside the combobox one?  I try to implement your library with simple input tag and display the suggestion with list tag, but many things are not working
(ps. with combobox everything was working fine, but I don't want to downgrade my react version)
Thanks

**Comment by wellyshen** [comment]
You can check the code of my [demo app](https://github.com/wellyshen/use-places-autocomplete/blob/master/app/src/App/index.tsx), which can help you build your own Combobox UI.
