### ISSUE TITLE
Limit the search to a specific area

### ISSUE THREAD

**Issue by demoox** [wellyshen/use-places-autocomplete#1131]
Good morning,
I've been racking my brains for about 2 days on this issue.

Indeed, I try to limit the search area to a specific area, in this case a country: the United States.

For this I added the following code:
` requestOptions: { componentRestrictions: { country: 'us' } },`

But it does not work because I have the addresses of the whole world which are displayed

Code : 
`
const PlacesAutocomplete = () => {

    const {
        ready,
        value,
        setValue,
        suggestions: { status, data },
        clearSuggestions,
    } = usePlacesAutocomplete({
        requestOptions: { componentRestrictions: { country: 'us' } },
        debounce: 300,
    });

    const handleSelect = async (address) => {
        setValue(address, false);
        clearSuggestions();

    };

    return (
        <Autocomplete
            options={data.map((option) => option.description)}
            noOptionsText="0 résultat"
            getOptionLabel={(option) => option}
            inputValue={value}
            onInputChange={(event, newValue) => {
                setValue(newValue);
            }}
            onChange={(event, newValue) => {
                if (typeof newValue === "string") {
                    handleSelect(newValue);
                }
            }}
            renderInput={(params) => (
                <TextField
                    {...params}
                    label="Adresse de livraison"
                    variant="outlined"
                    disabled={!ready}
                />
            )}
        />
    );
};
`

Would you have a solution?
Thanks

**Comment by demoox** [comment]
Sorry to say but this library is completely useless and causes more problems than anything else. prefer manual implementation than using it.

**Comment by eliawk** [comment]
Why this is closed? I have the same problem

**Comment by MoFerhat** [comment]
> Why this is closed? I have the same problem

Hi, try locationRestriction instead of componentRestrictions

**Comment by mygel-bergstresser-ck** [comment]
I am also running into the same issue. 

EDIT: You have to clear your cache after you update **componentRestrictions**
