### ISSUE TITLE
Add componentRestrictions for Geocoding

### ISSUE THREAD

**Issue by rue-wtemmerman** [wellyshen/use-places-autocomplete#127]
# Feature Request

## Describe the Feature

Right now the getGeocode method only accepts an address or a place id. 
The Google Geocoding service can accept a component restrictions parameter to restricted results to a specific area.

## Describe the Solution You'd Like

Update the getGeocode method to accept component restrictions as PlaceAutocomplete.

## Additional Information

If you have no time to do it, I can try to find some time to create a pull request this week.

**Comment by wellyshen** [comment]
@rue-wtemmerman I think you are talking about [this](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRequests). Yea, PR will be helpful 🙏🏻

**Comment by rue-wtemmerman** [comment]
> @rue-wtemmerman I think you are talking about [this](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRequests). Yea, PR will be helpful 🙏🏻

Exactly :)

I will try to do it this week ;)

**Comment by rejvban** [comment]
Hi guys, I had some free time and I thought to give it a try. :smile:

#135 Check it out if you have time

**Comment by wellyshen** [comment]
@rejvban Cool man, I will take time to review the PR soon 👍

**Comment by wellyshen** [comment]
This feature now available in [v1.2.0](https://github.com/wellyshen/use-places-autocomplete/releases/tag/v1.2.0), thank you guys 💯
