### ISSUE TITLE
Implement sessionToken to reduce costs even further

### ISSUE THREAD

**Issue by uanjoze** [wellyshen/use-places-autocomplete#137]
# Feature Request

## Describe the Feature

It's already great that you implemented debouncing to reduce API calls, but Google will nevertheless charge per each of these request. However, there's a parameter called sessionToken that can be sent to group one autocompletion and be charged only once.

These are some links about this feature:

Places API documentation
https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteSessionToken

They mentioned it when they introduced the pricing changes
https://cloud.google.com/maps-platform/user-guide/pricing-changes/

In the example for the query here it's all lowercased (so sessiontoken instead of sessionToken)
https://developers.google.com/places/web-service/usage-and-billing#ac-with-details-session

Thank you for making this React hook, by the way!

**Comment by wellyshen** [comment]
@uanjoze `sessionToken` can be set via the `requestOptions` as below, do you think it's enough?

```js
const return = usePlacesAutocomplete({
  requestOptions: {
    sessionToken: new google.maps.places.AutocompleteSessionToken(),
  }
});
```

**Comment by uanjoze** [comment]
Is the requestOptions object used just for initialising the component or can the contents be updated after initialisation?

An example would be a website where this autocomplete is used to add multiple locations, the hook initialises the component and then each location search would need its own sessionToken (so this would need to be re-set after every "autocomplete success"). This re-set can be done outside the usePlacesAutocomplete hook, of course, but then the requestOptions.sessionToken would change and I don't know if this change would be reflected within the hook.

I don't know if I'm explaining myself very well.

**Comment by wellyshen** [comment]
@uanjoze The `requestOptions` is the configuration of [getPlacePredictions](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteService.getPlacePredictions) method. This hook will use the latest properties of the `requestOptions` when it's mounted.

**Comment by uanjoze** [comment]
So renewing the session token after a selection has been made needs to be written outside of this hook. I just thought that it'd be handy (as this is all part of the autocompleting experience) to have it part of the hook, but it was only a suggestion :)

**Comment by wellyshen** [comment]
@uanjoze I will take time to understand how the `sessionToke` actually works then think about it.

**Comment by uanjoze** [comment]
If it's any help, this is how I've implemented it.

```javascript
const [requestNewSessionToken, setRequestNewSessionToken] = useState(true)
const [sessionToken, setSessionToken] = useState()

const getSessionToken = () => sessionToken

useEffect(() => {
  if (requestNewSessionToken) {
    setSessionToken(new google.maps.places.AutocompleteSessionToken())
    setRequestNewSessionToken(false)
  }
}, [requestNewSessionToken])
```

When I instantiate `usePlacesAutocomplete` I pass `sessionToken: getSessionToken()` and once I've autocompleted (on Google terms, once I've requested the details for the `placeId` for the selected item from the list) I just reset the token with `setRequestNewSessionToken(true)`

**Comment by wellyshen** [comment]
@uanjoze Did you mean you create a new session token for each request?

**Comment by uanjoze** [comment]
No, I create a new sessionToken per “autocomplete requests + final`getPlaceDetails` request” combo. I only reset this token when the user selects an item from the autocompleted list.

This only makes sense if you’re fetching the placeId information at the end of the autocomplete. If you’re only interested in lat and lng you can, of course, just get them from the info retourned by the autocomplete service.

**Comment by uanjoze** [comment]
Do you mean add the `sessionToken` functionality to the demo, for example? I can do that.

In the meantime, I've found a better explanation to why this is a good idea (billing-wise), from Google. https://developers.google.com/places/web-service/session-tokens

**Comment by jamesmosier** [comment]
I'm currently using session tokens with [react-places-autocomplete](https://github.com/hibiken/react-places-autocomplete) and have outlined the implementation below.

```jsx
const getSessionToken = () => new window.google.maps.places.AutocompleteSessionToken();

export const Autocomplete = props => {
  const { onSelect, searchOptions, ...restOfTheProps } = props;

  const [sessionToken, setSessionToken] = React.useState(getSessionToken());

  const handleSelect = (_address, _placeId) => {
    // refresh token after making a selection
    setSessionToken(getSessionToken());
    // set all the values we want in state when they select something
    onSelect(_address, _placeId);
  };

  return (
    <ReactPlacesAutocomplete
      {...restOfTheProps}
      onSelect={handleSelect}
      searchOptions={{
        ...searchOptions,
        sessionToken,
      }}
    />
  );
};
```

I think that implementation should be possible today with `use-places-autocomplete` by passing `sessionToken` in the `requestOptions` object.

Does that align with how you are using this @uanjoze?

**Comment by wellyshen** [comment]
Seems everyone has his/her way to generate the session token and transfer it to different APIs (e.g. place-autocomplete to place-detail). I'm still thinking if we need to provide the built-in session token feature (like generate, refresh, token property) for users 🤔

**Comment by uanjoze** [comment]
I see your point @wellyshen, and you're probably right. For Google a "search" can end with a request to place-detail or not (it can just be a bunch of place-autocomplete requests), so `sessionToken` is definitely useful and will reduce costs (I've seen a big drop in Google's invoice), but maybe it shouldn't be part of this hook (slight separation of concerns), so I'm closing the issue.

@jamesmosier that's pretty much how I've implemented it myself using `use-places-autocomplete` (the only difference is that I reset the token after the place-detail request and also if the suggestions are dismissed by clicking outside, or pressing the Esc key)

**Comment by binajmen** [comment]
Hi @uanjoze,

Could you please share an example on how you use the sessionToken? That would be really helpful 🙏

**Comment by uanjoze** [comment]
Hey @binajmen, you'll find half of this on this very [same thread](https://github.com/wellyshen/use-places-autocomplete/issues/137#issuecomment-617157971)

The other part is just passing the `sessionToken` over to the hook, like so:
```javascript
const {
    ready,
    value,
    suggestions: { status, data },
    setValue,
    clearSuggestions
  } = usePlacesAutocomplete({
    requestOptions: {
      sessionToken: getSessionToken()
    },
    debounce: 300
  })
```

**Comment by binajmen** [comment]
> Hey @binajmen, you'll find half of this on this very [same thread](https://github.com/wellyshen/use-places-autocomplete/issues/137#issuecomment-617157971)

I just wanted to double-check if that's still the good way, but it seems to work pretty well. Thanks for sharing, really helped!

**Comment by LuthandoMaqondo** [comment]
> @uanjoze `sessionToken` can be set via the `requestOptions` as below, do you think it's enough?
> 
> ```js
> const returnObject = usePlacesAutocomplete({
>   requestOptions: {
>     sessionToken: new google.maps.places.AutocompleteSessionToken(),
>   }
> });
> ```

This is exactly what I was looking for.
