### ISSUE TITLE
Demo isn't working due to API key not having domain set up.

### ISSUE THREAD

**Issue by mirshko** [wellyshen/use-places-autocomplete#138]
# Bug Report

## Describe the Bug

Demo app doesn't work https://use-places-autocomplete.netlify.app/

## How to Reproduce

Try to search on demo website

Error in console about API key not loading

## Screenshots

<img width="601" alt="Screen Shot 2020-04-20 at 10 06 13" src="https://user-images.githubusercontent.com/8116716/79728847-d70cf780-82ee-11ea-9e2f-3ac891a1fe97.png">

**Comment by wellyshen** [comment]
@mirshko Thank you I have fixed it.
