### ISSUE TITLE
Reverse geocoding with location in getGeocode

### ISSUE THREAD

**Issue by g1r0** [wellyshen/use-places-autocomplete#168]
Hello,

# Feature Request

## Describe the Feature
According to Google's documentation, the geocoder API [allows](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderRequest) doing that with location (LatLng) option. It would be nice to have it supported by GetGeocode too.

My use case is: I only have a LatLnt param and need to get the point's metadata.

## Describe the Solution You'd Like

I want to expand the GetGeocode's [interface](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/utils.ts#L4-L8) to have that option and add additional parameters validation. 

I'm asking about before doing any contribution, according to the project's recommendations.

Thank you.

**Comment by wellyshen** [comment]
@g1r0 The utility is designed for this hook, in general you should have the `placeId` or `address`. But your case is wired... why you only have the `location`?

**Comment by g1r0** [comment]
I have an address widget that has two ways to input the address:
- by place autocomplete (sometimes API just doesn't have an address to present in its DB);
- by a location picker, using the map.
In the second case, I need the reverse geocoding by location.

**Comment by wellyshen** [comment]
@g1r0 Alright, maybe we should allow all the options to cover more use cases 🤔. I'll spend time to do it. Thank you.

**Comment by wellyshen** [comment]
@g1r0 It has been supported in the latest version.
