### ISSUE TITLE
Missing features in demo

### ISSUE THREAD

**Issue by landworth** [wellyshen/use-places-autocomplete#174]
The documentation refers to a demo/code which is more UX rich including "a keyword clear button, search history"

Having implemented the code example I don't see these two features, so I'm wondering if I'm missing something here? Are there any code examples available for these two features?

Thanks

**Comment by wellyshen** [comment]
@landworth The demo app only contains "WAI-ARIA compliant and keyword support". Maybe I should write it more clearly, sorry my bad.

**Comment by wellyshen** [comment]
@landworth I try to keep the demo app as simple as possible. If you have any difficult for implementing these features you can send me a mail or open an issue in case I don't see your mail :)
