### ISSUE TITLE
Google requires you to display the required logos and attributions

### ISSUE THREAD

**Issue by manuganji** [wellyshen/use-places-autocomplete#179]
# Bug Report
Hey, the demo code doesn't have the Google logo and attributions and it violates the API use policy

## Expected Behavior

If this is out of the demo scope, we must at least add some text to make this clear.

## Screenshots

Add screenshots to help explain your problem.

## Your Environment

- OS: macOS
- Browser: Chrome
- Version: 1.2.3

## Additional Information

https://developers.google.com/maps/documentation/javascript/places-autocomplete#policies

**Comment by manuganji** [comment]
https://developers.google.com/places/web-service/policies#powered

**Comment by manuganji** [comment]
We can append this `<li>` to the `<ul>` at https://github.com/wellyshen/use-places-autocomplete/blob/master/demo/App/index.tsx#L165

`<li style={{
                textAlign: "center"
              }}>
                <img src="/images/powered_by_google/desktop/powered_by_google_on_white.png" />
              </li>`

**Comment by wellyshen** [comment]
@manuganji Thank you for telling me about it, I will add it soon.

**Comment by wellyshen** [comment]
@manuganji Google logo has been added to the demo app. Thank you.

**Comment by manuganji** [comment]
Wow, that's fast! You're awesome @wellyshen 💯 :)
