### ISSUE TITLE
Build an alternative UI demo using Reach UI Combobox

### ISSUE THREAD

**Issue by mirshko** [wellyshen/use-places-autocomplete#183]
It might be useful to create an alternative demo using https://reacttraining.com/reach-ui/combobox as it accomplices the same thing as what you're doing with the current demo with a proven solution as well. 

https://reacttraining.com/reach-ui/combobox

Might be worth looking into!

**Comment by wellyshen** [comment]
@mirshko There're many UI library open-sources, may I know why this one?

**Comment by mirshko** [comment]
Reach isn’t really a UI library per say, more of system of a11y friendly components to bring into your design system! 

Similar to Downshifts like methodology afaik!

**Comment by wellyshen** [comment]
@mirshko Interesting, I will spend time to try it. Thank you.

**Comment by mirshko** [comment]
For sure! 

Also i noticed that using the geocode helper performing the search with placeId over the address is sometimes 2-3x faster. might be worth suggesting. 

Ideally it’s unneeded as the address components could be returned in the initial search. 

Not sure if that’s possible?

**Comment by wellyshen** [comment]
@mirshko Could it be possible to find any reference for it?

**Comment by wellyshen** [comment]
@mirshko I have add the example of Reach UI, it's extremely easy to use the combobox with this hook indeed.

**Comment by mirshko** [comment]
Word! Looks good! 

Thanks for putting that up there! 

Only issue on my end using it is wondering if its possible to have a the `place_id` also passed to the handleSelect function.

Will let you know if I think of anything.

**Comment by wellyshen** [comment]
@mirshko I think they will support more custom data soon, see [here](https://github.com/reach/reach-ui/pull/514)
