### ISSUE TITLE
GLatLng not exported

### ISSUE THREAD

**Issue by apmcasai** [wellyshen/use-places-autocomplete#198]
# Bug Report
GLatLng not exported.

## Describe the Bug
Trying to use 

usePlacesAutocomplete({
    debounce: 300,
    requestOptions: {
      location: new GLatLng(19.419224, -99.171446),
    },
  })

But can't access GLatLng class since it's not exported.

## How to Reproduce

Run this code:

`import usePlacesAutocomplete, GLatLng, from "use-places-autocomplete"

usePlacesAutocomplete({
    debounce: 300,
    requestOptions: {
      location: new GLatLng(19.419224, -99.171446),
    },
  })`

GLatLng is expected but not exported in the module :(

## Expected Behavior

GLatLng should be expected

## Your Environment

- OS: macOS
- Browser Chrome
- Version of use-places-autocomplete: v1.0.4

**Comment by apmcasai** [comment]
Seems to be a type from @types/googlemaps, however I can't find and anyways it would be way easier to export it from this module devX-wise

**Comment by wellyshen** [comment]
@apmcasai Sorry for reporting this bug, I have corrected the type in the latest version. Regarding to the usage of `location` option, I think the correct way will be:

```js
usePlacesAutocomplete({
  debounce: 300,
  requestOptions: {
    // It's the method of google.maps
    location: new google.maps.LatLng(19.419224, -99.171446),
  },
})
```
