### ISSUE TITLE
Default location based on user's current location 

### ISSUE THREAD

**Issue by techyrajeev** [wellyshen/use-places-autocomplete#286]
# Feature Request

## Describe the Feature

A default location shown on the autocomplete input as soon as ui rendered.

## Describe the Solution You'd Like

If user's location is shared via browser geolocation api use that lat lang to display default location, user can change that obviously if needed. 
It should enabled via a config variable.
e.g 
`showCurrentLocationOnLoad: true | false`

**Comment by wellyshen** [comment]
@techyrajeev The process of getting default input value might involve user's permission and network errors. I think it's better to handle by developers, you can achieve it with the `getGeocode` utility as below:

```js
const { setValue } = usePlacesAutocomplete();

useEffect(() => {
  const success = (pos: any) => {
    const { latitude, longitude } = pos.coords;
    getGeocode({
      location: new google.maps.LatLng(latitude, longitude),
    }).then((results) => {
      setValue(results[0].formatted_address);
    });
  };

  const error = () => {
    console.log("> Unable to retrieve your location");
  };

  if (!navigator.geolocation) {
    console.log("> Geolocation is not supported by your browser");
  } else {
    navigator.geolocation.getCurrentPosition(success, error);
  }
}, [setValue]);
```
