### ISSUE TITLE
Moving {lat, lng} object between components as props

### ISSUE THREAD

**Issue by elibenton** [wellyshen/use-places-autocomplete#288]
Hi Welly!

I'm making a [web app](https://github.com/colanderworld/voter-quotient) where I'd like to pass the `{lat, lng}` object from the getGeocode Custom Hook to another component as a props. That component will these use each coordinate as a parameter to a Rest API request.

```jsx
getGeocode({ address: description })
			.then((results) => getLatLng(results[0]))
			.then(({ lat, lng }) => {
				console.log('📍 Coordinates: ', { lat, lng })
			})
			.catch((error) => {
				console.log('😱 Error: ', error)
			})
```

I think the part where I am getting hung up is the React's unidirectional data flow. I am having trouble getting the `{lat, lng}` object "back up" out of my [AddressInput.js](https://github.com/colanderworld/voter-quotient/blob/master/src/Components/AddressInput.js) component and into my "root" component [App.js](https://github.com/colanderworld/voter-quotient/blob/master/src/App.js), where I then want to pass `{lat, lng}` into another component as props. 

I realize that I am probably thinking about the app's structure the wrong way. Should I instead be calling the API in a `useEffect` Hook? Thanks in advance for any advice you may be able to provide!

**Comment by wellyshen** [comment]
@elibenton You can share states via [React Context API](https://reactjs.org/docs/context.html) or other state managements like [Redux](https://github.com/reduxjs/redux). I have created a demonstration via the React Context API for your case:

1. Create [a context for setting/getting the latlng values](https://github.com/wellyshen/voter-quotient/blob/master/src/Contexts/LatLng.js)
2. [Wrap the ancestor component of all the consumer components (that's let the App) with the Context.Provider](https://github.com/wellyshen/voter-quotient/blob/master/src/index.js#L10)
3. [Set the latlng values](https://github.com/wellyshen/voter-quotient/blob/master/src/Components/AddressInput.jsx#L60).
4. [Get the latlng values in any consumer components that you want](https://github.com/wellyshen/voter-quotient/blob/master/src/Components/Header.jsx#L19).

**Comment by elibenton** [comment]
Welly, this is amazingly helpful! Thank you so much for doing all of this!! :)

Best, Eli
