### ISSUE TITLE
reduce api usage costs with autocomplete sessions

### ISSUE THREAD

**Issue by ajendrex** [wellyshen/use-places-autocomplete#295]
Hello!

first of all, thanks for your work, I'm based mine of it :)

I'm concerned about the `getGeocode` utility and the fact that it doesn't use [PlacesService.getDetails](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails). I think it is important to be able to build a user session and reduce [API usage costs](https://developers.google.com/maps/billing/gmp-billing#ac-with-details-session) by specifying a [AutoCompleteSessionToken](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteSessionToken), which is currently supported by the `usePlacesAutocomplete` hook (in `requestOptions`) but not the `getGeocode` function.

Am I correct?

**Comment by wellyshen** [comment]
@ajendrex The `getGeocode` is based on the [Geocoding Service](https://developers.google.com/maps/documentation/javascript/geocoding). I didn't find any way for setting the session token like as the `usePlacesAutocomplete` hook. Seems it has [its own billing rule](https://developers.google.com/maps/documentation/geocoding/usage-and-billing).

**Comment by ajendrex** [comment]
You are right. Still, It would be useful to build an autocomplete session with places details by using an extra utility function from this package, which would in turn call to PlacesService.getDetails.

I am implementing it right now, it's being called `getPlaceDetails`. If it works, the API usage costs can be reduced by half!

I was instructed to make a PR to this repo at the end, so probably you'll see it soon.

greetings!

**Comment by wellyshen** [comment]
@ajendrex The main purpose of the `getGeocode` utility is to get the latitude and longitude but the `getPlaceDetails` doesn't provides them (see [here](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult)). Seems we still need the utility, I'm curious about your idea 👀

**Comment by ajendrex** [comment]
`latitude` and `longitude` come in `geometry` result of place details: https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceGeometry

**Comment by wellyshen** [comment]
@ajendrex Got it, please make sure the new idea has great DX and [useful information](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingResults) as the old one 👍
