### ISSUE TITLE
Using places hook multiple times on same page

### ISSUE THREAD

**Issue by sunilbittu** [wellyshen/use-places-autocomplete#338]
Can you suggest how can we use useplacesautocomplete hook multiple time on same page. Like say for from address and to address

**Comment by wellyshen** [comment]
How about combine an input with this hook to create an address component?

**Comment by sunilbittu** [comment]
I have done the implementation as @wellyshen  suggested and it working fine.

**Comment by Sushant-Borsania** [comment]
Hi Sunil, WellyShen,

Is it possible for you to share the code for implementing multiple useplacesautocomplete hook?

I am using this library and have a requirement to add as from, to, and dynamic via/waypoints locations.

Thank you.

**Comment by AmitAKB** [comment]
can you please tell us how you implement the places hooks in multiple times on the same page?

**Comment by aaronzhongg** [comment]
@sunilbittu @AmitAKB are you guys able to shed some light how you were able to do this?

I've created a component using the hook, however it appears as though only one of the callbacks are called on script load as only one of the component's `ready` returns true

**Comment by wellyshen** [comment]
@aaronzhongg Would you mind sharing your code with us for debugging?

**Comment by aaronzhongg** [comment]
@wellyshen Hey I got it working by using the non-async way of loading the script. At this stage it's good enough!

Thanks for the quick response btw :)

**Comment by khevamann** [comment]
See my comment here for multiple hooks with async https://github.com/wellyshen/use-places-autocomplete/issues/721#issuecomment-842727975
