### ISSUE TITLE
Missing language request parameter

### ISSUE THREAD

**Issue by adrian-marcelo-gallardo** [wellyshen/use-places-autocomplete#368]
# Bug Report

## Describe the Bug
The API specification lists a `language` parameter, but this library isn't including it as a valid option (not sure if it was an omission or if this parameter was recently added). 
https://developers.google.com/places/web-service/autocomplete

## How to Reproduce

Try to add the `language` parameter to `requestOptions` on a TS project, it will complain.

## Expected Behavior

`language` parameter should be accepted in `requestOptions` and it should be send to Google Autocomplete services

## Your Environment

- OS: macOs
- Browser Chrome
- Version of use-places-autocomplete: 1.3.10

**Comment by adrian-marcelo-gallardo** [comment]
BTW, it would be awesome if you could export the types defined by the library. I'd appreciate having access to `AutocompletionRequest`.

**Comment by wellyshen** [comment]
Hi @adrian-marcelo-gallardo I have checked it, the [AutocompletionRequest interface](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service) that this package is using, which doesn't include the `language ` option. You can try the [RequestOptions](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/use-places-autocomplete.d.ts#L139) type to see if it can solve your problem.

**Comment by adrian-marcelo-gallardo** [comment]
Thanks!, it seems the API supports the language parameter but the JS client doesn't (probably automatically read from the users' browser). Thanks for the support.
