### ISSUE TITLE
import AutocompletePrediction to handleSelect functions parameter type

### ISSUE THREAD

**Issue by franciscovaz** [wellyshen/use-places-autocomplete#369]
Hello, 
Could you export the types defined by the library? I'd appreciate having access to AutocompletePrediction, to add it to argument of handleSelect function.
Or there is another way to do it with typescript? 

Thank you 👍

**Comment by wellyshen** [comment]
@franciscovaz Actually, I have exported them. I think the [Suggestion](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/use-places-autocomplete.d.ts#L148) type is what you're looking for.

```js
import { Suggestion } from "usePlacesAutocomplete";
 
const handleSelect = ({ description }: Suggestion) => (): void => {
    setValue(description, false);
    dismissSuggestions();
  };
```

**Comment by franciscovaz** [comment]
@wellyshen  Yes, I had already done it, but i forgot to update the issue, sorry! 

Thank you for the response, and very nice work 💪
