### ISSUE TITLE
How to display "powered by Google" attribution? 

### ISSUE THREAD

**Issue by cyonder** [wellyshen/use-places-autocomplete#402]
I've checked the documentation but I can't find how to display the attribution. Is there any way to turn this on? 

Google docs says it's just an image. So, should I grab the attribution image from the [docs](https://developers.google.com/places/android-sdk/attributions) and serve it from my server or is there anyway to turn this on?

**Comment by wellyshen** [comment]
@cyonder It doesn't a part of this package. However you can visit my [demo code]（https://github.com/wellyshen/use-places-autocomplete/blob/6d00678b74c1ae593ccb0fe11ab8550d198e7aa2/demo/App/index.tsx#L115）to achieve it.
