### ISSUE TITLE
Ability to "setFields" with the getDetails function

### ISSUE THREAD

**Issue by vendrix-ds** [wellyshen/use-places-autocomplete#457]
When the getDetails function is called on a place id, it returns all the fields which you are charged for on each API call. Google Maps API autocomplete documentation has the following value to limit the data returned: 
autocomplete.setFields(["address_components", "geometry", "icon", "name"]); 
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Are these options able to be passed into the getDetails function?

**Comment by wellyshen** [comment]
@vendrix-ds [Current implementation only accepts the placeId](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/utils.ts#L78), but we can [add the fields option](https://developers.google.com/maps/documentation/javascript/places#place_details_requests) to meet your need.

**Comment by wellyshen** [comment]
@vendrix-ds [Here you are](https://github.com/wellyshen/use-places-autocomplete/releases/tag/v1.6.0).
