### ISSUE TITLE
Why was getDetails signature changed?

### ISSUE THREAD

**Issue by reharik** [wellyshen/use-places-autocomplete#524]
Hi, here
https://github.com/wellyshen/use-places-autocomplete/commit/a43e1b14aad34912c7dda9f76ffab36ee54e7165#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351L70
there is a change.  It used to be the case that if you passed in just the place_id it would work or if you passed in the "suggestion" it would pull the place_id out of it and it would work.
Now neither of those work you have pass in an object with a camelcased placeId on it.  This is not good. It is a breaking change for no advantage that I can tell.  I you want the sig to take `string | {place_id: string} | {placeId: string}` then that's find but why break it for those using it the old way?

**Comment by wellyshen** [comment]
Hi @reharik Sorry for the breaking change. The reason why I did the change as below, hope you can understanding:
- Reduce the charge fee of Google API by [include the fields](https://developers.google.com/maps/documentation/javascript/places#place_details_requests) arg. (#457)
- Align the API with the [getGeocode](https://github.com/wellyshen/use-places-autocomplete#getgeocode).

**Comment by reharik** [comment]
I see.  the docs helped.  I submitted a pr that added a bit of documentation to the readme.  
https://github.com/wellyshen/use-places-autocomplete/pull/528
Not sure if it's necessary, but I'll leave that up to y'all. 
Thanks
