### ISSUE TITLE
Cannot include sessionToken in request

### ISSUE THREAD

**Issue by blakeley** [wellyshen/use-places-autocomplete#544]
To reduce costs, Google requires autocomplete requests include a session token: https://developers.google.com/places/web-service/usage-and-billing

Passing in a simple string (for example, generated by uui()) passes typecheck, but then fails when making the request with the error: "in property sessionToken: not an instance of AutocompleteSessionToken", name: "InvalidValueError""

The top-level export file does not include the necessary class to create an AutocompleteSessionToken, meaning it is impossible to include a sessionToken in the request (without modifying this library)

**Comment by wellyshen** [comment]
@blakeley Did you pass your token via the [requestOptions](https://github.com/wellyshen/use-places-autocomplete#parameter-object-optional)?

**Comment by blakeley** [comment]
Yes

**Comment by wellyshen** [comment]
@blakeley Can you assign the token like below:

```js
const sessionToken = new google.maps.places.AutocompleteSessionToken();

const res = usePlacesAutocomplete({
  requestOptions: { sessionToken },
});
```

**Comment by blakeley** [comment]
Ah, I needed to add `@types/googlemaps` to be able to do that. But now there's a separate issue -- it looks like the session token is not actually included in the request headers. Maybe I'm misunderstanding where I could find the sessionToken?

**Comment by blakeley** [comment]
Ah, nevermind -- it looks like it's included as an URL parameter with an obfuscated key (`{.Aj: {Zg: ...}}` in my case)
