### ISSUE TITLE
TypeScript: `suggestions.data` is of type `any`

### ISSUE THREAD

**Issue by Aerophite** [wellyshen/use-places-autocomplete#551]
# Bug Report

## Describe the Bug

When using the autocomplete in TypeScript, `suggestions.data` is an array of type `any`. I believe this to be because `AutocompletePrediction` is `any` since it doesn't exist in the `index.d.ts` file. 

## How to Reproduce

```
import usePlacesAutocomplete from 'use-places-autocomplete';

export const AutocompleteLocation = (): JSX.Element => {
  const {
      suggestions: {
        data,
      },
      setValue,
    } = usePlacesAutocomplete({
      requestOptions: {
        componentRestrictions: { country: 'us' },
      },
      callbackName: 'loadPlaceAutocomplete',
      debounce: 300,
    });

    /**
     * The below will result in "Unsafe member access .description on an any value." since `data` is an array of `any`.
     * Note that I am seeing this when using typescript-eslint. 
     */
    data.map((suggestion) => suggestion.description);
};
```

## Expected Behavior

That `suggestions.data` is properly typed instead of `any`

## Screenshots

![image](https://user-images.githubusercontent.com/6826088/103563859-1da58080-4e83-11eb-8fd2-c6debadac10b.png)

## Your Environment

- Device: MacBook Pro (2017)
- OS: macOS Catalina version 10.15.7 (19H114)
- Browser: N/A
- Version: 1.7.0

## Additional Information

Any other information about the problem here.

**Comment by wellyshen** [comment]
@Aerophite Thank you for the bug reporting, it should be fixed in the latest version.
