### ISSUE TITLE
How that loading works of suggestions

### ISSUE THREAD

**Issue by Jakub41** [wellyshen/use-places-autocomplete#553]
Hello,

I have a query about the loading status in suggestions

```
const {
    ready,
    value: autocompleteValue,
    suggestions: { data, status, loading },
    clearSuggestions,
    setValue,
  } = usePlacesAutocomplete({
    debounce: 3000,
  });
```

This loading is very fast and the spinner I attached to show on loading appears for a millisecond and I would like to understand how to delay this or if there is a better way of doing it? 

I want to show up my loader spinner 

```
const isLoading = () => {
    return loading ? <CircularProgress color="inherit" size={20} /> : null;
  };
```

Thank you :)

**Comment by Lukasz-Semik** [comment]
Imo we should be super happy that we get data so fast :) 
I think, that this question is not regarding this package at all. 
You can simply create the internal state (in example: isLoading), when setting the value to search - set isLoading to true, at the end of this function use setTimeout to set is loading to false and then:

```
return loading || isLoading ? <Loader /> : something else
```

**Comment by Jakub41** [comment]
Thank you @Lukasz-Semik 
I'm happy is so fast but as per user UX, there is a moment like nothing happening. 
By the way, I solved this in a specific way by somehow using the loading with state and a timeout was doing exactly the same issue. 
By the way, I resolved the issue using a `useRef()` custom helper hook.
