### ISSUE TITLE
Do not make breaking changes without bumping the major version

### ISSUE THREAD

**Issue by gajus** [wellyshen/use-places-autocomplete#561]
# Bug Report

Several releases under `1.*.*` include breaking changes, but have not bumped the major version of the package.

https://github.com/wellyshen/use-places-autocomplete/releases

Semver dictates that once you release >=1.0.0 version, then all breaking changes necessitate major version increment.

Please increment the major version of the package the next time you are releasing breaking changes.

<img width="1170" alt="Screen Shot 2021-01-12 at 2 36 38 PM" src="https://user-images.githubusercontent.com/973543/104369791-9cce3080-54e3-11eb-942a-dd5093aeca59.png">
<img width="1188" alt="Screen Shot 2021-01-12 at 2 36 42 PM" src="https://user-images.githubusercontent.com/973543/104369796-9dff5d80-54e3-11eb-9c57-76e06b199ae4.png">

**Comment by wellyshen** [comment]
@gajus Seems I should pack these breaking changes into the next version 🤔. Alright, this package already be used by many users, let's follow the semver rules. Thanks for the suggestion.

**Comment by gajus** [comment]
Thank you @wellyshen ! We really appreciate the convenience of this library.
