### ISSUE TITLE
"requestOptions" parameter should be casted to "google.maps.places.AutocompleteOptions" instead of "google.maps.places.AutocompletionRequest"

### ISSUE THREAD

**Issue by majoncas** [wellyshen/use-places-autocomplete#564]
I started implementing your library which is really well done by the way but I've noticed that "requestOptions" parameter has the wrong type which forbids me to set "requestOptions.strictBounds = true". Changing type should allow me to fix my issue which is a very import feature to us (see https://developers.google.com/maps/documentation/javascript/reference/places-widget?hl=en#AutocompleteOptions).

Thank you in advance!

**Comment by wellyshen** [comment]
@majoncas Thank you for giving this library a try. The library is based on the [getPlacePredictions](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteService.getPlacePredictions) API. So, I think the type is correct.

**Comment by majoncas** [comment]
Thank you for your answer @wellyshen . Is there any workaround available to make work "strictBounds" option then?

**Comment by wellyshen** [comment]
@majoncas Maybe you can use the 'location' with 'radius' to meet your needs.

**Comment by majoncas** [comment]
Unfortunately this does not fulfill my need as this doesn't return the same results as if I was using the Places Widget :(

**Comment by wellyshen** [comment]
@majoncas Sorry for that, maybe you can fork this repo to fulfill your needs.
