### ISSUE TITLE
Query caching

### ISSUE THREAD

**Issue by majoncas** [wellyshen/use-places-autocomplete#568]
It would be great that this library offers out of the box caching of the results so we don't request new queries for the same inputed search criteria within the same user session. This could potentially help saving costs.

**Comment by wellyshen** [comment]
@majoncas Good idea, I will implement it soon.

**Comment by wellyshen** [comment]
@majoncas [Here you are](https://github.com/wellyshen/use-places-autocomplete/releases/tag/v1.8.0)

**Comment by majoncas** [comment]
Thank you so much @wellyshen ! Well done!
