### ISSUE TITLE
requestOptions seems to get ignored

### ISSUE THREAD

**Issue by imprex92** [wellyshen/use-places-autocomplete#586]
# Bug Report

## Describe the Bug
passing the **requestOptions** doesn't seem to work. Looking at the google doc [https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest](url) it should be possible to restrict results from an specific country by passing the property **componentRestrictions.country** with the country code. found here [https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#ComponentRestrictions](url)

I'm pretty new with react so maybe this isn't  bug but maybe I have done something wrong in my code.

## How to Reproduce
inside requestOptions, simply put 
```
componentRestrictions: {
      country: 'sv'
   }
```

## CodeSandbox Link
https://codesandbox.io/s/useplacesautocomplete-x-reach-ui-forked-qo84h
in the same demo as you already have. Look at **line 25** in this forked sandbox

## Expected Behavior

I expect this code to only show results from the country SV (sweden)
```
componentRestrictions: {
      country: 'sv'
   }
```

## Your Environment

- Device: [e.g. MacBook Pro, iPhone12]
- OS: [Windows]
- Browser: [Chrome]
- Version: [88.0]

I really like this! Except from this it works grate in my app! 
If this is not a bug, I would really appreciate help to get it to work !

**Comment by wellyshen** [comment]
@imprex92 The [AutocompletionRequest](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest) doesn't include the `country` property.

**Comment by wellyshen** [comment]
@imprex92 The value type of the `componentRestrictions` should be `string | string[]`, so try the following instead:

```js
componentRestrictions: 'sv'
```

**Comment by imprex92** [comment]
> @imprex92 The value type of the `componentRestrictions` should be `string | string[]`, so try the following instead:
> 
> ```js
> componentRestrictions: 'sv'
> ```

Hello @wellyshen! thank you for your reply. By changing it to a string like you mentioned didn't change anything unfortunately. I still get suggestions from any country, is there any other way I can achieve this?

**Comment by wellyshen** [comment]
@imprex92 Sorry my fault your setting is correct (as the following). And according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) the country code of Sweden should be `se`. Due to the [data cache] feature, I think you may be close the page after setting the config during developing.

```js
componentRestrictions: {
      country: 'se'
 }
```

**Comment by imprex92** [comment]
@wellyshen Hello again! Thank you! clearing the data cache along with `componentRestrictions: {    country: 'se' }` worked like a charm! 
for some reason the gecoding feature is returning "cannot read lat of undefined" now instead haha. I will see if I can find out the problem...

Thanks again for your help!

**Comment by wellyshen** [comment]
@imprex92 Nice keep going man.
