### ISSUE TITLE
how do we use setComponentRestrictions for suggesstions base on countries list like ["us", ...]

### ISSUE THREAD

**Issue by tabvn** [wellyshen/use-places-autocomplete#636]
Hi Everyone

is there way to access native api and use func setComponentRestrictions 

ex: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries#maps_places_autocomplete_multiple_countries-javascript

Best regards,
Toan

**Comment by tabvn** [comment]
i got answer

here is sample for someone need


````
const {
    ready,
    value,
    suggestions: { status, data },
    setValue,
    clearSuggestions,
  } = usePlacesAutocomplete({
    requestOptions: {
      /* Define search scope here */
      componentRestrictions: { country: ["us", "vn"] },
    },
    debounce: 300,
  });
```

**Comment by adisak1618** [comment]
Not work for me I restrict country but still got results from all over the place

**Comment by joaodfmota** [comment]
It's because the lib is using values in cache, if you clean up the session storage of the browser it will work as expected.

For now, I'm using this way:

```
cacheKey: 'br',
requestOptions: {
   componentRestrictions: { country: 'br' },
},
```

@adisak1618 @bandhanEA

**Comment by bandhanEA** [comment]
These are my request options that work for addresses in US

requestOptions: {
      componentRestrictions: { country: 'us' },
      types: ['address']
    },
    debounce: 300,
    cache: 24 * 60 * 60
  }
