### ISSUE TITLE
Google Maps JavaScript API warning: RetiredVersion

### ISSUE THREAD

**Issue by maurocolella** [wellyshen/use-places-autocomplete#658]
# Bug Report

## Describe the Bug

Hi. Thank you for this library. It appears that the Google Maps Javascript API might be outdated, see error message:
```
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

## How to Reproduce

Simply use the hook in normal form operation.

## Expected Behavior

Would be great if the warning was removed.

Thanks.

**Comment by wellyshen** [comment]
@maurocolella The version of Google Map API is controlled by your side.

**Comment by maurocolella** [comment]
@wellyshen yes. Looks fixed when using the weekly, 
https://developers.google.com/maps/documentation/javascript/versions

Thanks.
