### ISSUE TITLE
Multiple components

### ISSUE THREAD

**Issue by drbarzaga** [wellyshen/use-places-autocomplete#721]
Hi, I am using this package for creating a custom component but when I repeat my custom component 2 times the first component does not work because has the same class names as the second component. Please any idea?

![image](https://user-images.githubusercontent.com/12173976/117474423-42912980-af31-11eb-97b5-7b1e92a407a8.png)

**Comment by wellyshen** [comment]
@drbarzaga Please leave a minimal reproduce code via CodeSandbox or a repo, I will take time to review it.

**Comment by khevamann** [comment]
This same issue was addressed here. It seems as though the async method of loading the script does not allow for multiple components to be on the same page.

**Comment by khevamann** [comment]
If it helps I was able to make it work with async requests. The issue is finding a way to get the one script to call the multiple callback functions onLoad. The way I handled this was creating a function to inject the script.

```jsx
/**
 * Will set the callback for the given script
 */
function setupCallback(script: any, callback: () => void) {
  if (script.readyState) {
    script.onreadystatechange = function () {
      if (script.readyState === 'loaded' || script.readyState === 'complete') {
        script.onreadystatechange = null
        callback()
      }
    }
  } else {
    script.onload = () => {
      callback()
    }
  }
}

export const loadScript = (url: string, callback: () => void, id: string) => {
  let script: any
  if (document.getElementById(id)) {
    // If the script already exists then add the new callback to the existing one
    script = document.getElementById(id)
    const oldFunc = script.onload
    setupCallback(script, () => {
      oldFunc()
      callback()
    })
  } else {
    // If the script doesn't exists then create it
    script = document.createElement('script')
    script.type = 'text/javascript'
    script.src = url
    script.setAttribute('id', id)
    setupCallback(script, callback)
    document.getElementsByTagName('head')[0].appendChild(script)
  }
}
```

then when you create each component with usePlacesAutoComplete you can run this code to add the given initializer to the script tag.
```jsx
const { init } = usePlacesAutocomplete({
    initOnMount: false,
  })

  useEffect(() => {
    loadScript(
      `https://maps.googleapis.com/maps/api/js?key=[[API_KEY]]&libraries=places`,
      init,
      'google-maps-script',
    )
  }, [])
```

Let me know if you have any questions.

**Comment by wellyshen** [comment]
@drbarzaga Thank you for helping with this issue mate, I think we have the answer already.

**Comment by dlamprey** [comment]
@khevamann Thanks for sharing your solution to the problem I've been struggling with, though I haven't been able to get it to work. I suspect what may be missing is the part you mentioned as "add the given initializer to the script tag." can you elaborate on what you mean by that? Or even better would be an example that includes what I might be missing. I am a coding/react newbie and need to learn about useEffect.  Thanks in advance!

**Comment by khevamann** [comment]
Hi @dlamprey, below is a stripped down example of our implementation it is in React Native. Let me know if you have any questions on this or it isn't working.

```tsx
// Since we are including this place search on every page we only want to load the script once, so when we first use the
// component, we want to load the script and set initOnMount to false so that it doesn't try to use it before it is
// loaded all future occurrences should not wait for the script to load as it is already there and will never call
// the callback, so we set isFirstLoad to false and initOnMount to true
let isFirstLoad = true

export default function GooglePlacesSearch() {
  const {
    value,
    suggestions: { data, loading: searching },
    setValue,
    init,
  } = usePlacesAutocomplete({
    requestOptions: {
      componentRestrictions: { country: 'us' },
    },
    debounce: 300,
    initOnMount: !isFirstLoad,
    defaultValue: 'Current Location',
  })

  useEffect(() => {
    loadScript(
      `https://maps.googleapis.com/maps/api/js?key=${API_KEY}&callback=Function.prototype&libraries=places`,
      init,
      '__googleMapsScriptId',
    )
    isFirstLoad = false
  }, [])

  return (
    <>
      <TextInput
        value={value}
        onChange={(e) => setValue(e.nativeEvent.text)}
        placeholder="Search cities"
        //@ts-ignore: Chrome ignores 'off' values but respects a random string and won't try to autocomplete
        autoComplete="places-autocomplete"
        onSubmitEditing={console.log}
      />
      {data.map((val) => (
        <Text>{val.description}</Text>
      ))}
    </>
  )
}
```

**Comment by dlamprey** [comment]
@khevamann thank you so much for the lightning-fast and super-helpful response! your code example helped me get it working... though i am still debugging some type of race condition or blocking that prevents the autocomplete from working on the first load that happens intermittently - my favorite! 😢 i also had a painful lesson about how the special naming for server variables that are exposed on the client side.

**Comment by khevamann** [comment]
@dlamprey Glad that helped, if you create a code sandbox reproducing your issue I could help you try and get to the bottom of it. You can send it to my email
