### ISSUE TITLE
Lazily Initializing The Hook

### ISSUE THREAD

**Issue by nonoumasy** [wellyshen/use-places-autocomplete#751]
First of all, thanks for this library.
I'm trying to use this hook to initialize the Google api, however I have one question.
Where does useGoogleMapsApi() imported from?
```
import usePlacesAutocomplete from "use-places-autocomplete";

const App = () => {
  const { init } = usePlacesAutocomplete({
    initOnMount: false, // Disable initializing when the component mounts, default is true
  });

  const [loading] = useGoogleMapsApi({
    library: "places",
    onLoad: () => init(), // Lazily initializing the hook when the script is ready
  });

  return <div>{/* Some components... */}</div>;
};
```

**Comment by wellyshen** [comment]
@nonoumasy Thank you mate, it's just a presentative of a 3rd-party library, [like this one](https://github.com/wellyshen/use-places-autocomplete/issues/540#issuecomment-749560293)
