### ISSUE TITLE
Setting types in requestOptions results in Invalid Request

### ISSUE THREAD

**Issue by patrickShaikh** [wellyshen/use-places-autocomplete#761]
I'm trying to get only countrynames from Places API using types in requestOptions.

Accordingly to this documentation it should be possible
![image](https://user-images.githubusercontent.com/40237073/121199506-463b0780-c873-11eb-96ea-18d0a6ef335b.png)

Google's RequestOptions Doc: https://developers.google.com/maps/documentation/places/web-service/supported_types#table3

However when I execute this code here:
![image](https://user-images.githubusercontent.com/40237073/121361269-6d5a0d80-c935-11eb-81ab-6af87212c934.png)

I get this error:
![image](https://user-images.githubusercontent.com/40237073/121200234-de38f100-c873-11eb-8c6f-8986bf6ac435.png)

Expectate behaviour:
I expect it to show me only countrynames on proper input and nothing on bad input (when country does not start with searchstring it wont show anything.

Am I using it in a wrong way or is it really a bug?

**Comment by wellyshen** [comment]
@patrickShaikh Will take time to investigate this issue.

**Comment by patrickShaikh** [comment]
meanwhile i decided to continue with google's native api, which fits more my needs

during this i stumbled across this example here which covers the topic and i thought it might help your investigation
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries

**Comment by wellyshen** [comment]
@patrickShaikh Seems we're confused by the doc, try follows:

```js
const {/* ... */} = usePlacesAutocomplete({ requestOptions: { types: ["(regions)"] } });
```
