### ISSUE TITLE
Cors and invalid hook problem

### ISSUE THREAD

**Issue by ChinaraGuliyeva** [wellyshen/use-places-autocomplete#768]
Hello. I have an "Invalid hook call" and "Cors origin" problem with this library. How do you think, how can I fix it?

**Comment by wellyshen** [comment]
@ChinaraGuliyeva "CORS" is the issue of your server configuration, not this library. For the "invalid hook call" can you provide a reproduced repo or CodeSandbox, thank you.

**Comment by ChinaraGuliyeva** [comment]
Thank you! The problem was on my side. I think that today I've finally solved the issue with hooks. The problem was that I have had a project with an old version of React without hooks. We updated it, but It not fully. React and React-dom was up to date, but not React-hot-loader. 

Maybe this will be helpful for others, who work with old React versions and update them for using hooks, some outdated libraries may cause problems.
