### ISSUE TITLE
Status does not return anything if an error has occurred fetching api

### ISSUE THREAD

**Issue by treyshedrick** [wellyshen/use-places-autocomplete#881]
# Have status send back ERROR if unable to fetch api

## Describe the Solution You'd Like
Have status return "ERROR" if unable to fetch from api

## A clear and concise description of what you want to happen.
Have status return "ERROR" if unable to fetch from api

## Describe Alternatives You've Considered

Tried making boolean errorFetching based on the loading, status, and data states.

## Additional Information

When testing with an invalid api key or going offline, there does not seem a way to display an error has occurred. It would be great if this lib would incorporate something into its usePlacesAutocomplete hook.

Example google api error that can occur that does not result in any changes in the status
![Screen Shot 2021-11-09 at 12 08 36 PM](https://user-images.githubusercontent.com/35882658/140980166-51e760a1-0063-4055-a874-511a421aefa0.png)

**Comment by wellyshen** [comment]
@treyshedrick Thank you for this feedback, will take time to check if we can do this.

**Comment by wellyshen** [comment]
@treyshedrick These errors are throw by Google Map SDK internally, we're not able to catch them.
