### ISSUE TITLE
TypeScript error in (....)/node_modules/use-places-autocomplete/dist/index.d.ts(21,24): Type expected.  TS1110

### ISSUE THREAD

**Issue by Bartaf83** [wellyshen/use-places-autocomplete#899]
# Bug Report

## Bug description

Typescript fails to compile, i'm getting this error:
(......)/node_modules/use-places-autocomplete/dist/index.d.ts
TypeScript error in (....)/node_modules/use-places-autocomplete/dist/index.d.ts(21,24):
Type expected.  TS1110

## How to Reproduce

Just installed "use-places-autocomplete": "^1.11.0"

## Screenshots

![image](https://user-images.githubusercontent.com/12170979/144580007-a3d39fd1-d5ab-47b7-940b-8a65c3b1c686.png)

## Environment

"react": "^16.14.0",
"webpack": "4.42.0",
"@babel/cli": "^7.12.10",
"@babel/core": "^7.12.10",

**Comment by krishhopkins** [comment]
Hey I am actually seeing the same issue and I see you closed this. Would you mind sharing what solved your issue?
