### ISSUE TITLE
Which service SKU does component use ?

### ISSUE THREAD

**Issue by djedlajn** [wellyshen/use-places-autocomplete#90]
Due to expected high volume of request goign to Places API i was wondering what kind of SKU do you use under the hood to make request some are free and some are whoping $17 per 1k requests.

See more :  [Basic SKU](https://developers.google.com/places/web-service/usage-and-billing#basic-data)

Overall its such a nice component good job.

**Comment by wellyshen** [comment]
@djedlajn Good question. This hook is based on the [Places Autocomplete Service](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteService). (refer to [here](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/usePlacesAutocomplete.ts#L57)). So I think it should be [SKU: Autocomplete - Per Request](https://developers.google.com/places/web-service/usage-and-billing#ac-per-request).

**Comment by PExplorer** [comment]
Thank you Wellyshen for great component. It really helped me to quickly tryout maps for my application. How can we change settings to request only Basic SKU (https://developers.google.com/maps/documentation/places/web-service/usage-and-billing#basic-data) if I need lat,lng of selected suggestion?
