### ISSUE TITLE
Type Expected in index.d.ts

### ISSUE THREAD

**Issue by chrissx520** [wellyshen/use-places-autocomplete#914]
# Bug Report

## Describe the Bug

Trying to bundle fails on line 21

`export type Status = `${google.maps.places.PlacesServiceStatus}` | "";`

## How to Reproduce

`react-app-rewired build`

Steps to reproduce the behavior, please provide code snippets or a repository:

Just compiling a project with the library.

```
TypeScript error in /home/christopher/tango/admin/node_modules/use-places-autocomplete/dist/index.d.ts(21,24):
Type expected.  TS1110

    19 |   export type Suggestion = google.maps.places.AutocompletePrediction;
    20 | 
  > 21 |   export type Status = `${google.maps.places.PlacesServiceStatus}` | "";
       |                        ^
    22 | 
    23 |   export interface Suggestions {
    24 |     readonly loading: boolean;

```

## Expected Behavior

Clean compilation.

## Additional Information

When switching to `export type Status = google.maps.places.PlacesServiceStatus;`

the build succeeds

**Comment by wellyshen** [comment]
@chrissx520 Do you mind to share the repo with me for debugging?
