### ISSUE TITLE
Cache key not updating on change

### ISSUE THREAD

**Issue by sallomendo** [wellyshen/use-places-autocomplete#952]
# Bug Report

## Describe the Bug

`fetchPredictions` callback is not updating when `cache` or `cacheKey` changes.

## How to Reproduce

When the cache key is stateful, the window storage key doesn't change.

```
const [countryCode, setCountryCode] = useState("US")

const autocomplete = usePlacesAutocomplete({
    cacheKey: countryCode
});
```

## Expected Behavior

The cache and cache key should change when you pass a different value.

## Your Environment

- Device: MacBook Pro
- OS: macOS
- Browser: Chrome
- Version: 1.11.0

## Additional Information

I think we need to add `cache` and `cacheKey` as a dependency to the `useCallback` hook here https://github.com/wellyshen/use-places-autocomplete/blob/master/src/usePlacesAutocomplete.ts#L155

**Comment by wellyshen** [comment]
@sallomendo Should we need to remove the cache when the key is updated?

**Comment by sallomendo** [comment]
@wellyshen I don’t think so, we can use the clearCache function inside a useEffect hook, I think we should leave that to the dev.

**Comment by wellyshen** [comment]
@sallomendo Sorry quite busy recently, would you mind to give me a PR for this issue?

**Comment by wellyshen** [comment]
@sallomendo This issue has been fixed in the [latest version](https://github.com/wellyshen/use-places-autocomplete/releases/tag/v2.0.0).

**Comment by sallomendo** [comment]
@wellyshen thanks for working on this, I will close the pr I created for this.

**Comment by wellyshen** [comment]
@sallomendo Sorry I didn't note that, thank you!
