### ISSUE TITLE
Is there any way to change the language of the results?

### ISSUE THREAD

**Issue by ifmael** [wellyshen/use-places-autocomplete#973]
I would like to get the results in Spanish  but i don't find the way to do it with this hook and i don't know if it could be possible

**Comment by wangela** [comment]
You can set the language as a parameter of the script loading URL. https://developers.google.com/maps/documentation/javascript/url-params

To set to Spanish, you would use `&language="es"` for Spanish or `&language="es-419"` for Spanish (Latin America), as documented in the [supported languages](https://developers.google.com/maps/faq#languagesupport)
