### ISSUE TITLE
Does getLatLng util really need to be async?

### ISSUE THREAD

**Issue by RavenHursT** [wellyshen/use-places-autocomplete#998]
Wondering why this is `async`? Is there some reason it _has_ to be? 🤔 

https://github.com/wellyshen/use-places-autocomplete/blob/master/src/utils.ts#L31-L40

I'm using this simple synchronous function in my code and it seems to be working fine.  No need to call w/ `await`, or have an `async` consumer this way:

```js
const getLatLng = (address = {}) => {
  const {
    geometry: {
      location: {
        lat = noop,
        lng = noop
      } = {}
    } = {}
  } = address

  return {
    lat: lat(),
    lng: lng()
  }
}
```

**Comment by RavenHursT** [comment]
@wellyshen ☝️

**Comment by wellyshen** [comment]
@RavenHursT Awesome bro, will review it soon 🤩

**Comment by wellyshen** [comment]
Close due to #1002
